name: PHPStan Static Analyzer
on:
  push:
    branches:
    - master
    - v1
    - v2
    - v3
    - v4
    - v5
  pull_request:
jobs:
  run-phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    permissions:
      # for github/codeql-action/upload-sarif to upload SARIF results
      security-events: write
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: json, xdebug
        tools: composer:v2

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Connect downloaded dependencies with a cache in GitHub
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        # Note: Normally, we'd use the composer.lock to generate a hash,
        # but the lock file is currently not versioned.
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Audit dependencies
      run: composer audit

    - name: Run PHPStan
      continue-on-error: true
      run: vendor/bin/phpstan analyze --error-format=sarif > phpstan-results.sarif

    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: phpstan-results.sarif
        wait-for-processing: true
